---

- name: Downloading the EPEL repository definitions.
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest={{ nagios_download_dir }}/epel-release-6-8.noarch.rpm
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Downloading and enable the EPEL repository definitions.
  yum: name={{ nagios_download_dir }}//epel-release-6-8.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Downloading and enable the EPEL repository definitions.
  yum: name=epel-release state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: install apache
  yum: pkg={{ item }} state=present
  with_items:
   - php
   - httpd
   - libsemanage-python
   - libselinux-python

- name: Install Nagios prerequisites for CentOS
  yum: pkg={{ item }} state=present
  with_items:
   - gcc
   - glibc
   - glibc-common
   - gd
   - gd-devel
   - make
   - perl
   - perl-devel
   - wget
   - python-passlib
   - unzip

- name: Install plugin prerequisites for CentOS
  yum: pkg={{ item }} state=present
  with_items:
   - openssl-devel
   - fping
   - openldap-devel
   - postgresql-devel
   - radiusclient-ng-devel
   - samba-client
   - libsmbclient

- name: Install NRPE prerequisites
  yum: pkg={{ item }} state=present
  with_items:
   - gcc
   - glibc
   - glibc-common
   - make
   - openssl-devel

