---
- name: Import epel gpg key
  ansible.builtin.rpm_key:
    key: "{{ epel_repo_gpg_key_path }}"
    state: present
  tags:
    - epel
  when: ansible_os_family == 'RedHat'

- name: Install epel repo
  ansible.builtin.dnf:
    name: "{{ epel_repo_url }}"
    state: present
  tags:
    - epel
  when: ansible_os_family == 'RedHat'

# To enable powertools, see next step
- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int > 7

# For certain Perl modules to be available
- name: Install powertools
  ansible.builtin.command: dnf config-manager --set-enabled powertools
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int > 7
  changed_when: false

- name: Install apache
  ansible.builtin.dnf:
    name: "{{ nagios_apache_packages }}"
    state: present

- name: Install Nagios prerequisites for CentOS
  ansible.builtin.dnf:
    name: "{{ nagios_prerequisite_packages }}"
    state: present

- name: Install plugin prerequisites for CentOS
  ansible.builtin.dnf:
    name: "{{ nagios_plugin_packages }}"
    state: present

- name: Install NRPE prerequisites
  ansible.builtin.dnf:
    name: "{{ nagios_nrpe_prerequisite_packages }}"
    state: present

- name: Install nagios python packages
  ansible.builtin.dnf:
    name: "{{ nagios_python_packages }}"
    state: present

- name: Install passlib
  ansible.builtin.dnf:
    name: python3-passlib
    state: present
